### ISSUE TITLE
Legende zur Abbildung 14

### ISSUE THREAD

**Issue by RadioMan57** [HB9UF/nanovna_workshop#1]
Die Legende zur Abbildung 14 passt nicht zur Abbildung. Der Text ist eine Kopie der Legende zur Abbildung 12.

**Comment by mweyland** [comment]
Hallo und vielen Dank! Das war das erste Mal, dass jemand via github einen Fehler im Dokument rapportiert. Ich habe das im Quelltext korrigiert. In der nächsten Version (1.2) wird die Legende korrekt abgedruckt sein.

Grüsse und nochmals danke
Mathias
